# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf ~/drone
            mkdir -p ~/drone/
            cd ~/drone/
            git clone https://github.com/toxuh/drone-weather-backend.git
            cd drone-weather-backend
            touch .env
            echo APP_HOST=${{ secrets.APP_HOST }} >> .env
            echo APP_PORT=${{ secrets.APP_PORT }} >> .env
            echo DB_USER=${{ secrets.DB_USER }} >> .env
            echo DB_PASSWORD =${{ secrets.DB_PASSWORD }} >> .env
            echo DB_COLLECTION =${{ secrets.DB_COLLECTION }} >> .env
            npm install
            npm run build
            pm2 delete node-test
            pm2 start dist/app.js --name node-test
